language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

notifications:
  - email: false

branches:
  only:
    - master
    - dev

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build test
